name: chartlets
channels:
  - conda-forge
dependencies:
  # Library Dependencies
  - python >=3.10,<3.14
  # Optional Dependencies
  - altair
  # Demo Dependencies
  - pandas
  - pyaml
  - tornado
  # Dev Dependencies
  - black
  - flake8
  - pytest
  - pytest-cov
  - requests-mock
